# Generated by Django 2.2.1 on 2019-05-18 14:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='temps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100)),
                ('message', ckeditor.fields.RichTextField(blank=True, default='Email Template- Is Blank!')),
                ('delay', models.IntegerField(default=456)),
                ('model_pic_1', models.ImageField(blank=True, null=True, upload_to='Model_pics/')),
                ('model_pic_2', models.ImageField(blank=True, null=True, upload_to='Model_pics/')),
                ('model_pic_3', models.ImageField(blank=True, null=True, upload_to='Model_pics/')),
                ('model_pic_4', models.ImageField(blank=True, null=True, upload_to='Model_pics/')),
                ('model_pic_5', models.ImageField(blank=True, null=True, upload_to='Model_pics/')),
                ('model_pic_6', models.ImageField(blank=True, null=True, upload_to='Model_pics/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=False)),
                ('ison', models.BooleanField(default=False)),
                ('uconfig', jsonfield.fields.JSONField(blank=True, default={'emaill': 'Email Is Empty!', 'host_con': 'not ok', 'imap': 'IMAP Is Empty!', 'link1': 'example.com', 'link2': 'example.com', 'name': 'Name Is Empty!', 'pass': 'Password Is Empty!', 'port': 'Port Is Empty!', 'smtp': 'SMTP Is Empty!'})),
                ('webmails', jsonfield.fields.JSONField(blank=True, default={})),
                ('ucont', jsonfield.fields.JSONField(blank=True, default={})),
                ('bcont', jsonfield.fields.JSONField(blank=True, default={'blacklist': [], 'blocked': []})),
                ('econt', jsonfield.fields.JSONField(blank=True, default={})),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queuelist', jsonfield.fields.JSONField(blank=True, default={})),
                ('sentlistlist', jsonfield.fields.JSONField(blank=True, default={})),
                ('failedlist', jsonfield.fields.JSONField(blank=True, default={})),
                ('elist', jsonfield.fields.JSONField(blank=True, default={})),
                ('User', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
